In [16]:
%matplotlib notebook

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import os
import seaborn as sns
import pandas as pd
import gpp

data_path = "./data"
dataset = np.load(os.path.join(data_path, 'pendulum_v0_imgs.npz'))
data_details = pd.read_pickle(os.path.join(data_path, 'pendulum_v0_details.pkl'))
data_latent = np.load(os.path.join(data_path, 'pendulum_v0_latent_kl2rl1-z6-b100.npz'))['arr_0']

In [3]:
raw_obs = np.array(data_details['raw_obs'].tolist())
x, y = raw_obs[:, :2].T

In [4]:
data_details

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>episode</th>
      <th>image_index</th>
      <th>pendulum_length</th>
      <th>pendulum_mass</th>
      <th>raw_action</th>
      <th>raw_obs</th>
      <th>reward</th>
      <th>step</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>0</td>
      <td>1.257675</td>
      <td>1.396678</td>
      <td>[0.0]</td>
      <td>[-0.2934452649406187, 0.955975876517776, -0.28...</td>
      <td>-3.499721</td>
      <td>0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0</td>
      <td>1</td>
      <td>1.257675</td>
      <td>1.396678</td>
      <td>[0.4110535]</td>
      <td>[-0.3162528337380962, 0.9486749417754345, 0.47...</td>
      <td>-3.604943</td>
      <td>1</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0</td>
      <td>2</td>
      <td>1.257675</td>
      <td>1.396678</td>
      <td>[0.17953274]</td>
      <td>[-0.37302253140839425, 0.9278222842019228, 1.2...</td>
      <td>-3.960829</td>
      <td>2</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0</td>
      <td>3</td>
      <td>1.257675</td>
      <td>1.396678</td>
      <td>[-0.3053808]</td>
      <td>[-0.4581436152391949, 0.8888781850262502, 1.87...</td>
      <td>-4.539828</td>
      <td>3</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0</td>
      <td>4</td>
      <td>1.257675</td>
      <td>1.396678</td>
      <td>[0.58357644]</td>
      <td>[-0.5695952580252172, 0.8219253263132766, 2.60...</td>
      <td>-5.415962</td>
      <td>4</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0</td>
      <td>5</td>
      <td>1.257675</td>
      <td>1.396678</td>
      <td>[-0.24965115]</td>
      <td>[-0.6929716263338626, 0.7209648570465842, 3.19...</td>
      <td>-6.477573</td>
      <td>5</td>
    </tr>
    <tr>
      <th>6</th>
      <td>0</td>
      <td>6</td>
      <td>1.257675</td>
      <td>1.396678</td>
      <td>[1.5670921]</td>
      <td>[-0.8195603330449615, 0.572992897424769, 3.900...</td>
      <td>-7.932276</td>
      <td>6</td>
    </tr>
    <tr>
      <th>7</th>
      <td>0</td>
      <td>7</td>
      <td>1.257675</td>
      <td>1.396678</td>
      <td>[1.8546511]</td>
      <td>[-0.9272986273046441, 0.37432239553481556, 4.5...</td>
      <td>-9.661456</td>
      <td>7</td>
    </tr>
    <tr>
      <th>8</th>
      <td>0</td>
      <td>8</td>
      <td>1.257675</td>
      <td>1.396678</td>
      <td>[-0.46623394]</td>
      <td>[-0.9894124500982655, 0.14513098769920701, 4.7...</td>
      <td>-11.242069</td>
      <td>8</td>
    </tr>
    <tr>
      <th>9</th>
      <td>0</td>
      <td>9</td>
      <td>1.257675</td>
      <td>1.396678</td>
      <td>[1.1669002]</td>
      <td>[-0.9945881751644238, -0.10389591822156204, 4....</td>
      <td>-11.722407</td>
      <td>9</td>
    </tr>
    <tr>
      <th>10</th>
      <td>0</td>
      <td>10</td>
      <td>1.257675</td>
      <td>1.396678</td>
      <td>[0.11557968]</td>
      <td>[-0.9391883014218679, -0.34340258367156545, 4....</td>
      <td>-10.219579</td>
      <td>10</td>
    </tr>
    <tr>
      <th>11</th>
      <td>0</td>
      <td>11</td>
      <td>1.257675</td>
      <td>1.396678</td>
      <td>[0.27217823]</td>
      <td>[-0.8333944133516222, -0.5526787057543519, 4.7...</td>
      <td>-8.743008</td>
      <td>11</td>
    </tr>
    <tr>
      <th>12</th>
      <td>0</td>
      <td>12</td>
      <td>1.257675</td>
      <td>1.396678</td>
      <td>[1.7023865]</td>
      <td>[-0.6902015116264311, -0.7236172146574386, 4.4...</td>
      <td>-7.441016</td>
      <td>12</td>
    </tr>
    <tr>
      <th>13</th>
      <td>0</td>
      <td>13</td>
      <td>1.257675</td>
      <td>1.396678</td>
      <td>[-1.7158557]</td>
     

In [5]:
thetas = np.arctan2(y, x)
rewards = np.array(data_details['reward'])
pendulum_mass = np.array(data_details['pendulum_mass'])
pendulum_length = np.array(data_details['pendulum_length'])
actions = np.array(data_details['raw_action'].tolist())

In [8]:
actions

array([[ 0.        ],
       [ 0.4110535 ],
       [ 0.17953274],
       ...,
       [-1.5210258 ],
       [-0.9810532 ],
       [ 1.3136857 ]], dtype=float32)

In [6]:
def angle_normalize(x):
    return np.fmod(x + np.pi, 2*np.pi) - np.pi

In [7]:
selected_idx = [2, 4, 5]
selected_latent = data_latent.reshape(len(raw_obs), -1)[:, selected_idx]

In [13]:
foo = np.concatenate([thetas.reshape(-1, 1), x.reshape(-1, 1), y.reshape(-1, 1), rewards.reshape(-1, 1), actions, data_latent.reshape(len(raw_obs), -1)], axis=1)
foo = pd.DataFrame(foo, columns=('theta', 'y', 'x', 'rewards', 'actions', 'z_0', 'z_1', 'z_2', 'z_3', 'z_4', 'z_5'))
foo

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>theta</th>
      <th>y</th>
      <th>x</th>
      <th>rewards</th>
      <th>actions</th>
      <th>z_0</th>
      <th>z_1</th>
      <th>z_2</th>
      <th>z_3</th>
      <th>z_4</th>
      <th>z_5</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1.868625</td>
      <td>-0.293445</td>
      <td>0.955976</td>
      <td>-3.499721</td>
      <td>0.000000</td>
      <td>-1.110664</td>
      <td>-0.235117</td>
      <td>-2.275965</td>
      <td>1.017740</td>
      <td>0.756314</td>
      <td>-0.111232</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1.892573</td>
      <td>-0.316253</td>
      <td>0.948675</td>
      <td>-3.604943</td>
      <td>0.411054</td>
      <td>2.031200</td>
      <td>0.848054</td>
      <td>-2.296019</td>
      <td>0.119952</td>
      <td>-1.232879</td>
      <td>-0.114479</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1.953061</td>
      <td>-0.373023</td>
      <td>0.927822</td>
      <td>-3.960829</td>
      <td>0.179533</td>
      <td>-0.911096</td>
      <td>0.971694</td>
      <td>-2.164225</td>
      <td>-0.613819</td>
      <td>-1.110937</td>
      <td>-0.235363</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2.046702</td>
      <td>-0.458144</td>
      <td>0.888878</td>
      <td>-4.539828</td>
      <td>-0.305381</td>
      <td>1.268697</td>
      <td>0.003526</td>
      <td>-2.106858</td>
      <td>0.534819</td>
      <td>-1.259176</td>
      <td>-0.426444</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2.176810</td>
      <td>-0.569595</td>
      <td>0.821925</td>
      <td>-5.415962</td>
      <td>0.583576</td>
      <td>0.246391</td>
      <td>-0.584006</td>
      <td>-1.863585</td>
      <td>1.255274</td>
      <td>-1.016348</td>
      <td>-0.628818</td>
    </tr>
    <tr>
      <th>5</th>
      <td>2.336399</td>
      <td>-0.692972</td>
      <td>0.720965</td>
      <td>-6.477573</td>
      <td>-0.249651</td>
      <td>-0.077283</td>
      <td>1.941471</td>
      <td>-1.661291</td>
      <td>1.368833</td>
      <td>-1.095649</td>
      <td>-0.907334</td>
    </tr>
    <tr>
      <th>6</th>
      <td>2.531440</td>
      <td>-0.819560</td>
      <td>0.572993</td>
      <td>-7.932276</td>
      <td>1.567092</td>
      <td>1.402149</td>
      <td>-0.014090</td>
      <td>-1.442459</td>
      <td>2.460960</td>
      <td>-0.043828</td>
      <td>-1.251124</td>
    </tr>
    <tr>
      <th>7</th>
      <td>2.757927</td>
      <td>-0.927299</td>
      <td>0.374322</td>
      <td>-9.661456</td>
      <td>1.854651</td>
      <td>-0.924540</td>
      <td>-0.819793</td>
      <td>-1.044047</td>
      <td>-1.299220</td>
      <td>0.992399</td>
      <td>-1.771260</td>
    </tr>
    <tr>
      <th>8</th>
      <td>2.995947</td>
      <td>-0.989412</td>
      <td>0.145131</td>
      <td>-11.242069</td>
      <td>-0.466234</td>
      <td>-1.059472</td>
      <td>0.121774</td>
      <td>-0.520577</td>
      <td>0.164422</td>
      <td>-1.388684</td>
      <td>-2.270768</td>
    </tr>
    <tr>
      <th>9</th>
      <td>-3.037509</td>
      <td>-0.994588</td>
      <td>-0.103896</td>
      <td>-11.722407</td>
      <td>1.166900</td>
      <td>1.263611</td>
      <td>1.249524</td>
      <td>0.332348</td>
      <td>0.193123</td>
      <td>-0.879948</td>
      <td>-1.936894</td>
    </tr>
    <tr>
      <th>10</th>
      <td>-2.791055</td>
      <td>-0.939188</td>
      <td>-0.343403</td>
      <td>-10.219579</td>
      <td>0.115580</td>
      <td>-0.727918</td>
      <td>0.452511</td>
      <td>0.961019</td>
      <td>0.442009</td>
      <td>-1.409028</td>
      <td>-1.529915</td>
    </tr>
    <tr>
      <th>11</th>
      <td>-2.556018

In [17]:
sns.pairplot(foo, x_vars=('theta','rewards', 'x', 'y', 'actions'), y_vars=('z_0', 'z_1', 'z_2', 'z_3', 'z_4', 'z_5'))

<IPython.core.display.Javascript object>

<div id='bbd4aada-90a3-42f0-964a-edf14d900a3d'></div>

In [11]:
sns.pairplot(foo, vars=('x', 'y'))

<IPython.core.display.Javascript object>

<div id='13110f4d-62e5-4424-b207-4bc38dbde119'></div>

In [16]:
bar = np.concatenate([pendulum_mass.reshape(-1, 1), pendulum_length.reshape(-1, 1), data_latent.reshape(len(raw_obs), -1)], axis=1)
bar = pd.DataFrame(bar, columns=('pendulum_mass', 'pendulum_length', 'z_0', 'z_1', 'z_2', 'z_3', 'z_4', 'z_5'))

In [17]:
sns.pairplot(bar, x_vars=('pendulum_mass', 'pendulum_length'), y_vars=('z_0', 'z_1', 'z_2', 'z_3', 'z_4', 'z_5'))

<IPython.core.display.Javascript object>

<div id='36751bc8-fa5d-414d-9e76-614f9a4cf695'></div>

In [18]:
sns.pairplot(bar, vars=('z_0', 'z_1', 'z_2', 'z_3', 'z_4', 'z_5'))

<IPython.core.display.Javascript object>

<div id='2fb57c15-58e0-4636-8a35-1adb81665a78'></div>

In [21]:
angle_normalize(thetas).reshape(-1, 1)

array([[1.86862511],
       [1.89257331],
       [1.95306088],
       ...,
       [1.99661227],
       [1.88568225],
       [1.83245328]])

In [22]:
thetas

array([1.86862511, 1.89257331, 1.95306088, ..., 1.99661227, 1.88568225,
       1.83245328])

In [23]:
sns.distplot(angle_normalize(thetas)**2)

C:\Users\PierLuigi\PycharmProjects\generative-parametrizations\venv\lib\site-packages\scipy\stats\stats.py:1713: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval


In [24]:
sns.distplot(rewards)

C:\Users\PierLuigi\PycharmProjects\generative-parametrizations\venv\lib\site-packages\scipy\stats\stats.py:1713: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval
